package engine

import (
	"time"

	"github.com/zakyalvan/krtlwrkflw/authz"
	"github.com/zakyalvan/krtlwrkflw/humantask"
)

// Command is the sealed set of side effects the core asks the runtime to
// perform. The unexported marker keeps the set closed.
type Command interface {
	isCommand()
}

// TimerKind discriminates the purpose of a scheduled timer.
type TimerKind int

const (
	// TimerIntermediate is a timer on an intermediate catch event node.
	TimerIntermediate TimerKind = iota
	// TimerSLA is a deadline timer that fires when an SLA is breached.
	TimerSLA
	// TimerInWait is a recurring in-wait timer (e.g. reminder) that fires
	// periodically during a wait period.
	TimerInWait
)

// String returns the name of the TimerKind for debugging/logging.
func (k TimerKind) String() string {
	switch k {
	case TimerIntermediate:
		return "TimerIntermediate"
	case TimerSLA:
		return "TimerSLA"
	case TimerInWait:
		return "TimerInWait"
	default:
		return "TimerKind(unknown)"
	}
}

// ScheduleTimer asks the runtime to schedule a timer that will deliver a
// TimerFired trigger at FireAt. Kind distinguishes intermediate, SLA, and
// in-wait timers so the runtime can apply the right scheduling policy.
type ScheduleTimer struct {
	TimerID string
	Token   string
	FireAt  time.Time
	Kind    TimerKind
}

// CancelTimer asks the runtime to cancel a previously scheduled timer.
type CancelTimer struct {
	TimerID string
}

// InvokeAction asks the runtime to run a named ServiceAction. Its result
// returns as an ActionCompleted/ActionFailed trigger carrying the same CommandID.
type InvokeAction struct {
	CommandID string
	Name      string
	Input     map[string]any
}

// CompleteInstance marks the instance complete with a result.
type CompleteInstance struct {
	Result map[string]any
}

// FailInstance marks the instance failed.
type FailInstance struct {
	Err string
}

// AwaitHuman asks the runtime to create a human-task record and park the engine
// until a HumanCompleted trigger arrives. Eligibility describes who may act.
type AwaitHuman struct {
	TaskToken   string
	Eligibility authz.AuthzSpec
}

// UpdateTask asks the runtime to persist an updated [humantask.HumanTask] record
// (e.g. after a claim or reassignment).
type UpdateTask struct {
	Task humantask.HumanTask
}

// ThrowSignal asks the runtime to broadcast a named signal to all interested
// subscribers (other process instances or external listeners). It is emitted
// when execution passes through a KindIntermediateThrowEvent node whose
// SignalName is set. The runtime is responsible for delivering the signal;
// the engine continues past the throw node without waiting for delivery.
type ThrowSignal struct {
	Name    string
	Payload map[string]any
}

// StartSubInstance asks the runtime to start a new child process instance for
// the given process definition reference. The result is correlated back to the
// parent via CommandID: a SubInstanceCompleted or SubInstanceFailed trigger
// carrying the same CommandID will resume the waiting parent token.
//
// Input is the initial variables passed into the child instance. The parent
// engine state must not be mutated after emitting this command (the calling
// convention of Step guarantees this via cloneState).
//
// Note: the drive-behavior (parking the parent token and routing the result
// back) is implemented in Task 3+. This command type is defined here so that
// the sealed Command set is extended atomically with the trigger types.
type StartSubInstance struct {
	// CommandID is a unique identifier generated by the engine (via CmdSeq)
	// used to correlate the child's completion/failure back to this command.
	CommandID string
	// DefRef is the process definition reference (ID, or "ID:version") for the
	// child process to start. Resolution is left to the runtime.
	DefRef string
	// Input is the initial variable map passed to the child instance. May be nil.
	Input map[string]any
}

// Compensate is an engine-internal command that drives reverse-order compensation
// for a specific execution scope. It is emitted on cancel/error paths that want
// to compensate a scope before terminating. ScopeID identifies the scope to
// compensate ("" = root scope); FromNode is the node from which the reverse
// walk starts (the most recently completed node, or "" for all records in scope).
//
// This command is handled by the runtime/orchestration layer (not by Step
// directly); Step uses CompensateRequested (a Trigger) for the admin-driven path.
// The shared reverse-walk logic (compensationWalk) is reused by both paths.
type Compensate struct {
	// ScopeID identifies the execution scope to compensate. Empty = root scope.
	ScopeID string
	// FromNode is the BPMN node ID to compensate FROM (the most recent completed node).
	// Empty means compensate ALL records in the scope.
	FromNode string
}

func (InvokeAction) isCommand()      {}
func (CompleteInstance) isCommand()  {}
func (FailInstance) isCommand()      {}
func (AwaitHuman) isCommand()        {}
func (UpdateTask) isCommand()        {}
func (ScheduleTimer) isCommand()     {}
func (CancelTimer) isCommand()       {}
func (ThrowSignal) isCommand()       {}
func (StartSubInstance) isCommand()  {}
func (Compensate) isCommand()        {}

// Compile-time assertions: Compensate must satisfy Command.
var _ Command = Compensate{}
