// Code generated by MockGen. DO NOT EDIT.
// Source: deadletter.go
//
// Generated by this command:
//
//	mockgen -source=deadletter.go -package=service -destination=deadletter_mock.go -typed
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	monitor "github.com/kartaladev/wrkflw/runtime/monitor"
	gomock "go.uber.org/mock/gomock"
)

// MockDeadLetterAdmin is a mock of DeadLetterAdmin interface.
type MockDeadLetterAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockDeadLetterAdminMockRecorder
	isgomock struct{}
}

// MockDeadLetterAdminMockRecorder is the mock recorder for MockDeadLetterAdmin.
type MockDeadLetterAdminMockRecorder struct {
	mock *MockDeadLetterAdmin
}

// NewMockDeadLetterAdmin creates a new mock instance.
func NewMockDeadLetterAdmin(ctrl *gomock.Controller) *MockDeadLetterAdmin {
	mock := &MockDeadLetterAdmin{ctrl: ctrl}
	mock.recorder = &MockDeadLetterAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeadLetterAdmin) EXPECT() *MockDeadLetterAdminMockRecorder {
	return m.recorder
}

// ListDeadLettered mocks base method.
func (m *MockDeadLetterAdmin) ListDeadLettered(ctx context.Context, limit int) ([]monitor.DeadLetter, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListDeadLettered", ctx, limit)
	ret0, _ := ret[0].([]monitor.DeadLetter)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListDeadLettered indicates an expected call of ListDeadLettered.
func (mr *MockDeadLetterAdminMockRecorder) ListDeadLettered(ctx, limit any) *MockDeadLetterAdminListDeadLetteredCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListDeadLettered", reflect.TypeOf((*MockDeadLetterAdmin)(nil).ListDeadLettered), ctx, limit)
	return &MockDeadLetterAdminListDeadLetteredCall{Call: call}
}

// MockDeadLetterAdminListDeadLetteredCall wrap *gomock.Call
type MockDeadLetterAdminListDeadLetteredCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeadLetterAdminListDeadLetteredCall) Return(arg0 []monitor.DeadLetter, arg1 error) *MockDeadLetterAdminListDeadLetteredCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeadLetterAdminListDeadLetteredCall) Do(f func(context.Context, int) ([]monitor.DeadLetter, error)) *MockDeadLetterAdminListDeadLetteredCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeadLetterAdminListDeadLetteredCall) DoAndReturn(f func(context.Context, int) ([]monitor.DeadLetter, error)) *MockDeadLetterAdminListDeadLetteredCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Redrive mocks base method.
func (m *MockDeadLetterAdmin) Redrive(ctx context.Context, ids ...int64) (int, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range ids {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Redrive", varargs...)
	ret0, _ := ret[0].(int)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Redrive indicates an expected call of Redrive.
func (mr *MockDeadLetterAdminMockRecorder) Redrive(ctx any, ids ...any) *MockDeadLetterAdminRedriveCall {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, ids...)
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Redrive", reflect.TypeOf((*MockDeadLetterAdmin)(nil).Redrive), varargs...)
	return &MockDeadLetterAdminRedriveCall{Call: call}
}

// MockDeadLetterAdminRedriveCall wrap *gomock.Call
type MockDeadLetterAdminRedriveCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockDeadLetterAdminRedriveCall) Return(arg0 int, arg1 error) *MockDeadLetterAdminRedriveCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockDeadLetterAdminRedriveCall) Do(f func(context.Context, ...int64) (int, error)) *MockDeadLetterAdminRedriveCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockDeadLetterAdminRedriveCall) DoAndReturn(f func(context.Context, ...int64) (int, error)) *MockDeadLetterAdminRedriveCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
