// Code generated by MockGen. DO NOT EDIT.
// Source: lineage.go
//
// Generated by this command:
//
//	mockgen -source=lineage.go -package=service -destination=lineage_mock.go -typed
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	kernel "github.com/kartaladev/wrkflw/runtime/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockLineageAdmin is a mock of LineageAdmin interface.
type MockLineageAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockLineageAdminMockRecorder
	isgomock struct{}
}

// MockLineageAdminMockRecorder is the mock recorder for MockLineageAdmin.
type MockLineageAdminMockRecorder struct {
	mock *MockLineageAdmin
}

// NewMockLineageAdmin creates a new mock instance.
func NewMockLineageAdmin(ctrl *gomock.Controller) *MockLineageAdmin {
	mock := &MockLineageAdmin{ctrl: ctrl}
	mock.recorder = &MockLineageAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLineageAdmin) EXPECT() *MockLineageAdminMockRecorder {
	return m.recorder
}

// Lineage mocks base method.
func (m *MockLineageAdmin) Lineage(ctx context.Context, instanceID string) (kernel.InstanceLineage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lineage", ctx, instanceID)
	ret0, _ := ret[0].(kernel.InstanceLineage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Lineage indicates an expected call of Lineage.
func (mr *MockLineageAdminMockRecorder) Lineage(ctx, instanceID any) *MockLineageAdminLineageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lineage", reflect.TypeOf((*MockLineageAdmin)(nil).Lineage), ctx, instanceID)
	return &MockLineageAdminLineageCall{Call: call}
}

// MockLineageAdminLineageCall wrap *gomock.Call
type MockLineageAdminLineageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockLineageAdminLineageCall) Return(arg0 kernel.InstanceLineage, arg1 error) *MockLineageAdminLineageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockLineageAdminLineageCall) Do(f func(context.Context, string) (kernel.InstanceLineage, error)) *MockLineageAdminLineageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockLineageAdminLineageCall) DoAndReturn(f func(context.Context, string) (kernel.InstanceLineage, error)) *MockLineageAdminLineageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
