// Code generated by MockGen. DO NOT EDIT.
// Source: policyadmin.go
//
// Generated by this command:
//
//	mockgen -source=policyadmin.go -package=service -destination=policyadmin_mock.go -typed
//

// Package service is a generated GoMock package.
package service

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockPolicyAdmin is a mock of PolicyAdmin interface.
type MockPolicyAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockPolicyAdminMockRecorder
	isgomock struct{}
}

// MockPolicyAdminMockRecorder is the mock recorder for MockPolicyAdmin.
type MockPolicyAdminMockRecorder struct {
	mock *MockPolicyAdmin
}

// NewMockPolicyAdmin creates a new mock instance.
func NewMockPolicyAdmin(ctrl *gomock.Controller) *MockPolicyAdmin {
	mock := &MockPolicyAdmin{ctrl: ctrl}
	mock.recorder = &MockPolicyAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPolicyAdmin) EXPECT() *MockPolicyAdminMockRecorder {
	return m.recorder
}

// AddPolicy mocks base method.
func (m *MockPolicyAdmin) AddPolicy(ctx context.Context, rule PolicyRule) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddPolicy", ctx, rule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddPolicy indicates an expected call of AddPolicy.
func (mr *MockPolicyAdminMockRecorder) AddPolicy(ctx, rule any) *MockPolicyAdminAddPolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddPolicy", reflect.TypeOf((*MockPolicyAdmin)(nil).AddPolicy), ctx, rule)
	return &MockPolicyAdminAddPolicyCall{Call: call}
}

// MockPolicyAdminAddPolicyCall wrap *gomock.Call
type MockPolicyAdminAddPolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminAddPolicyCall) Return(arg0 bool, arg1 error) *MockPolicyAdminAddPolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminAddPolicyCall) Do(f func(context.Context, PolicyRule) (bool, error)) *MockPolicyAdminAddPolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminAddPolicyCall) DoAndReturn(f func(context.Context, PolicyRule) (bool, error)) *MockPolicyAdminAddPolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// AddRole mocks base method.
func (m *MockPolicyAdmin) AddRole(ctx context.Context, binding RoleBinding) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddRole", ctx, binding)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AddRole indicates an expected call of AddRole.
func (mr *MockPolicyAdminMockRecorder) AddRole(ctx, binding any) *MockPolicyAdminAddRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddRole", reflect.TypeOf((*MockPolicyAdmin)(nil).AddRole), ctx, binding)
	return &MockPolicyAdminAddRoleCall{Call: call}
}

// MockPolicyAdminAddRoleCall wrap *gomock.Call
type MockPolicyAdminAddRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminAddRoleCall) Return(arg0 bool, arg1 error) *MockPolicyAdminAddRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminAddRoleCall) Do(f func(context.Context, RoleBinding) (bool, error)) *MockPolicyAdminAddRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminAddRoleCall) DoAndReturn(f func(context.Context, RoleBinding) (bool, error)) *MockPolicyAdminAddRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListPolicies mocks base method.
func (m *MockPolicyAdmin) ListPolicies(ctx context.Context) ([]PolicyRule, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListPolicies", ctx)
	ret0, _ := ret[0].([]PolicyRule)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListPolicies indicates an expected call of ListPolicies.
func (mr *MockPolicyAdminMockRecorder) ListPolicies(ctx any) *MockPolicyAdminListPoliciesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListPolicies", reflect.TypeOf((*MockPolicyAdmin)(nil).ListPolicies), ctx)
	return &MockPolicyAdminListPoliciesCall{Call: call}
}

// MockPolicyAdminListPoliciesCall wrap *gomock.Call
type MockPolicyAdminListPoliciesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminListPoliciesCall) Return(arg0 []PolicyRule, arg1 error) *MockPolicyAdminListPoliciesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminListPoliciesCall) Do(f func(context.Context) ([]PolicyRule, error)) *MockPolicyAdminListPoliciesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminListPoliciesCall) DoAndReturn(f func(context.Context) ([]PolicyRule, error)) *MockPolicyAdminListPoliciesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// ListRoles mocks base method.
func (m *MockPolicyAdmin) ListRoles(ctx context.Context) ([]RoleBinding, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRoles", ctx)
	ret0, _ := ret[0].([]RoleBinding)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRoles indicates an expected call of ListRoles.
func (mr *MockPolicyAdminMockRecorder) ListRoles(ctx any) *MockPolicyAdminListRolesCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRoles", reflect.TypeOf((*MockPolicyAdmin)(nil).ListRoles), ctx)
	return &MockPolicyAdminListRolesCall{Call: call}
}

// MockPolicyAdminListRolesCall wrap *gomock.Call
type MockPolicyAdminListRolesCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminListRolesCall) Return(arg0 []RoleBinding, arg1 error) *MockPolicyAdminListRolesCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminListRolesCall) Do(f func(context.Context) ([]RoleBinding, error)) *MockPolicyAdminListRolesCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminListRolesCall) DoAndReturn(f func(context.Context) ([]RoleBinding, error)) *MockPolicyAdminListRolesCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemovePolicy mocks base method.
func (m *MockPolicyAdmin) RemovePolicy(ctx context.Context, rule PolicyRule) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemovePolicy", ctx, rule)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemovePolicy indicates an expected call of RemovePolicy.
func (mr *MockPolicyAdminMockRecorder) RemovePolicy(ctx, rule any) *MockPolicyAdminRemovePolicyCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemovePolicy", reflect.TypeOf((*MockPolicyAdmin)(nil).RemovePolicy), ctx, rule)
	return &MockPolicyAdminRemovePolicyCall{Call: call}
}

// MockPolicyAdminRemovePolicyCall wrap *gomock.Call
type MockPolicyAdminRemovePolicyCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminRemovePolicyCall) Return(arg0 bool, arg1 error) *MockPolicyAdminRemovePolicyCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminRemovePolicyCall) Do(f func(context.Context, PolicyRule) (bool, error)) *MockPolicyAdminRemovePolicyCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminRemovePolicyCall) DoAndReturn(f func(context.Context, PolicyRule) (bool, error)) *MockPolicyAdminRemovePolicyCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// RemoveRole mocks base method.
func (m *MockPolicyAdmin) RemoveRole(ctx context.Context, binding RoleBinding) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveRole", ctx, binding)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RemoveRole indicates an expected call of RemoveRole.
func (mr *MockPolicyAdminMockRecorder) RemoveRole(ctx, binding any) *MockPolicyAdminRemoveRoleCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveRole", reflect.TypeOf((*MockPolicyAdmin)(nil).RemoveRole), ctx, binding)
	return &MockPolicyAdminRemoveRoleCall{Call: call}
}

// MockPolicyAdminRemoveRoleCall wrap *gomock.Call
type MockPolicyAdminRemoveRoleCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockPolicyAdminRemoveRoleCall) Return(arg0 bool, arg1 error) *MockPolicyAdminRemoveRoleCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockPolicyAdminRemoveRoleCall) Do(f func(context.Context, RoleBinding) (bool, error)) *MockPolicyAdminRemoveRoleCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockPolicyAdminRemoveRoleCall) DoAndReturn(f func(context.Context, RoleBinding) (bool, error)) *MockPolicyAdminRemoveRoleCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
