// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: workflow.proto

package workflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_StartInstance_FullMethodName       = "/wrkflw.v1.WorkflowService/StartInstance"
	WorkflowService_GetInstance_FullMethodName         = "/wrkflw.v1.WorkflowService/GetInstance"
	WorkflowService_DeliverSignal_FullMethodName       = "/wrkflw.v1.WorkflowService/DeliverSignal"
	WorkflowService_DeliverMessage_FullMethodName      = "/wrkflw.v1.WorkflowService/DeliverMessage"
	WorkflowService_ClaimTask_FullMethodName           = "/wrkflw.v1.WorkflowService/ClaimTask"
	WorkflowService_CompleteTask_FullMethodName        = "/wrkflw.v1.WorkflowService/CompleteTask"
	WorkflowService_ReassignTask_FullMethodName        = "/wrkflw.v1.WorkflowService/ReassignTask"
	WorkflowService_ListInstances_FullMethodName       = "/wrkflw.v1.WorkflowService/ListInstances"
	WorkflowService_CancelInstance_FullMethodName      = "/wrkflw.v1.WorkflowService/CancelInstance"
	WorkflowService_ResolveIncident_FullMethodName     = "/wrkflw.v1.WorkflowService/ResolveIncident"
	WorkflowService_ListDeadLetters_FullMethodName     = "/wrkflw.v1.WorkflowService/ListDeadLetters"
	WorkflowService_RedriveDeadLetters_FullMethodName  = "/wrkflw.v1.WorkflowService/RedriveDeadLetters"
	WorkflowService_GetInstanceSnapshot_FullMethodName = "/wrkflw.v1.WorkflowService/GetInstanceSnapshot"
	WorkflowService_GetActionableView_FullMethodName   = "/wrkflw.v1.WorkflowService/GetActionableView"
	WorkflowService_AddPolicy_FullMethodName           = "/wrkflw.v1.WorkflowService/AddPolicy"
	WorkflowService_RemovePolicy_FullMethodName        = "/wrkflw.v1.WorkflowService/RemovePolicy"
	WorkflowService_ListPolicies_FullMethodName        = "/wrkflw.v1.WorkflowService/ListPolicies"
	WorkflowService_AddRole_FullMethodName             = "/wrkflw.v1.WorkflowService/AddRole"
	WorkflowService_RemoveRole_FullMethodName          = "/wrkflw.v1.WorkflowService/RemoveRole"
	WorkflowService_ListRoles_FullMethodName           = "/wrkflw.v1.WorkflowService/ListRoles"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkflowService exposes the workflow engine's Service facade over gRPC.
// Consumers register this service on their own grpc.Server via
// RegisterWorkflowServiceServer; this package never owns a listener.
type WorkflowServiceClient interface {
	// StartInstance creates and starts a new process instance from a definition.
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// GetInstance returns the current state of an existing instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// DeliverSignal resumes a parked instance by delivering a named signal.
	DeliverSignal(ctx context.Context, in *DeliverSignalRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// DeliverMessage routes a message to the waiting instance by (name, correlation key).
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error)
	// ClaimTask authorizes the actor and claims a human task.
	ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// CompleteTask authorizes the actor and completes a human task.
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ReassignTask authorizes the reassigner and reassigns a human task.
	ReassignTask(ctx context.Context, in *ReassignTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ListInstances returns a paginated list of instance summaries.
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// CancelInstance terminates a running instance (running cancel actions best-effort).
	CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ResolveIncident clears an open incident, grants additional attempts, and resumes execution.
	ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ListDeadLetters returns dead-lettered outbox rows. Admin-scoped; requires the
	// server to be registered with WithDeadLetterAdmin, else returns Unimplemented.
	ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error)
	// RedriveDeadLetters re-queues dead outbox rows by id. Admin-scoped; requires
	// WithDeadLetterAdmin, else returns Unimplemented.
	RedriveDeadLetters(ctx context.Context, in *RedriveDeadLettersRequest, opts ...grpc.CallOption) (*RedriveDeadLettersResponse, error)
	// GetInstanceSnapshot returns the full snapshot projection of an instance,
	// including tokens, history, tasks, incidents, and action-binding metadata.
	GetInstanceSnapshot(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceSnapshotResponse, error)
	// GetActionableView returns the actionable projection of an instance: open
	// human tasks and their allowed next actions derived from the definition.
	GetActionableView(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*ActionableViewResponse, error)
	// AddPolicy adds a casbin permission rule. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	AddPolicy(ctx context.Context, in *AddPolicyRequest, opts ...grpc.CallOption) (*MutateAck, error)
	// RemovePolicy removes a casbin permission rule. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*MutateAck, error)
	// ListPolicies returns all permission rules. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error)
	// AddRole adds a casbin role assignment. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*MutateAck, error)
	// RemoveRole removes a casbin role assignment. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*MutateAck, error)
	// ListRoles returns all role assignments. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeliverSignal(ctx context.Context, in *DeliverSignalRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DeliverSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverMessageResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReassignTask(ctx context.Context, in *ReassignTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ReassignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CancelInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ResolveIncident(ctx context.Context, in *ResolveIncidentRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ResolveIncident_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListDeadLetters(ctx context.Context, in *ListDeadLettersRequest, opts ...grpc.CallOption) (*ListDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDeadLettersResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RedriveDeadLetters(ctx context.Context, in *RedriveDeadLettersRequest, opts ...grpc.CallOption) (*RedriveDeadLettersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedriveDeadLettersResponse)
	err := c.cc.Invoke(ctx, WorkflowService_RedriveDeadLetters_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetInstanceSnapshot(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceSnapshotResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetInstanceSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetActionableView(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*ActionableViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ActionableViewResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetActionableView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AddPolicy(ctx context.Context, in *AddPolicyRequest, opts ...grpc.CallOption) (*MutateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateAck)
	err := c.cc.Invoke(ctx, WorkflowService_AddPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RemovePolicy(ctx context.Context, in *RemovePolicyRequest, opts ...grpc.CallOption) (*MutateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateAck)
	err := c.cc.Invoke(ctx, WorkflowService_RemovePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListPolicies(ctx context.Context, in *ListPoliciesRequest, opts ...grpc.CallOption) (*ListPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListPoliciesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) AddRole(ctx context.Context, in *AddRoleRequest, opts ...grpc.CallOption) (*MutateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateAck)
	err := c.cc.Invoke(ctx, WorkflowService_AddRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) RemoveRole(ctx context.Context, in *RemoveRoleRequest, opts ...grpc.CallOption) (*MutateAck, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MutateAck)
	err := c.cc.Invoke(ctx, WorkflowService_RemoveRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListRoles(ctx context.Context, in *ListRolesRequest, opts ...grpc.CallOption) (*ListRolesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRolesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListRoles_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
//
// WorkflowService exposes the workflow engine's Service facade over gRPC.
// Consumers register this service on their own grpc.Server via
// RegisterWorkflowServiceServer; this package never owns a listener.
type WorkflowServiceServer interface {
	// StartInstance creates and starts a new process instance from a definition.
	StartInstance(context.Context, *StartInstanceRequest) (*InstanceResponse, error)
	// GetInstance returns the current state of an existing instance.
	GetInstance(context.Context, *GetInstanceRequest) (*InstanceResponse, error)
	// DeliverSignal resumes a parked instance by delivering a named signal.
	DeliverSignal(context.Context, *DeliverSignalRequest) (*InstanceResponse, error)
	// DeliverMessage routes a message to the waiting instance by (name, correlation key).
	DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error)
	// ClaimTask authorizes the actor and claims a human task.
	ClaimTask(context.Context, *ClaimTaskRequest) (*InstanceResponse, error)
	// CompleteTask authorizes the actor and completes a human task.
	CompleteTask(context.Context, *CompleteTaskRequest) (*InstanceResponse, error)
	// ReassignTask authorizes the reassigner and reassigns a human task.
	ReassignTask(context.Context, *ReassignTaskRequest) (*InstanceResponse, error)
	// ListInstances returns a paginated list of instance summaries.
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// CancelInstance terminates a running instance (running cancel actions best-effort).
	CancelInstance(context.Context, *CancelInstanceRequest) (*InstanceResponse, error)
	// ResolveIncident clears an open incident, grants additional attempts, and resumes execution.
	ResolveIncident(context.Context, *ResolveIncidentRequest) (*InstanceResponse, error)
	// ListDeadLetters returns dead-lettered outbox rows. Admin-scoped; requires the
	// server to be registered with WithDeadLetterAdmin, else returns Unimplemented.
	ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error)
	// RedriveDeadLetters re-queues dead outbox rows by id. Admin-scoped; requires
	// WithDeadLetterAdmin, else returns Unimplemented.
	RedriveDeadLetters(context.Context, *RedriveDeadLettersRequest) (*RedriveDeadLettersResponse, error)
	// GetInstanceSnapshot returns the full snapshot projection of an instance,
	// including tokens, history, tasks, incidents, and action-binding metadata.
	GetInstanceSnapshot(context.Context, *GetInstanceRequest) (*InstanceSnapshotResponse, error)
	// GetActionableView returns the actionable projection of an instance: open
	// human tasks and their allowed next actions derived from the definition.
	GetActionableView(context.Context, *GetInstanceRequest) (*ActionableViewResponse, error)
	// AddPolicy adds a casbin permission rule. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	AddPolicy(context.Context, *AddPolicyRequest) (*MutateAck, error)
	// RemovePolicy removes a casbin permission rule. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	RemovePolicy(context.Context, *RemovePolicyRequest) (*MutateAck, error)
	// ListPolicies returns all permission rules. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error)
	// AddRole adds a casbin role assignment. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	AddRole(context.Context, *AddRoleRequest) (*MutateAck, error)
	// RemoveRole removes a casbin role assignment. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	RemoveRole(context.Context, *RemoveRoleRequest) (*MutateAck, error)
	// ListRoles returns all role assignments. Admin-scoped; requires
	// WithPolicyAdmin, else returns Unimplemented.
	ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) DeliverSignal(context.Context, *DeliverSignalRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverSignal not implemented")
}
func (UnimplementedWorkflowServiceServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedWorkflowServiceServer) ClaimTask(context.Context, *ClaimTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedWorkflowServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ReassignTask(context.Context, *ReassignTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReassignTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWorkflowServiceServer) CancelInstance(context.Context, *CancelInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) ResolveIncident(context.Context, *ResolveIncidentRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ResolveIncident not implemented")
}
func (UnimplementedWorkflowServiceServer) ListDeadLetters(context.Context, *ListDeadLettersRequest) (*ListDeadLettersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDeadLetters not implemented")
}
func (UnimplementedWorkflowServiceServer) RedriveDeadLetters(context.Context, *RedriveDeadLettersRequest) (*RedriveDeadLettersResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RedriveDeadLetters not implemented")
}
func (UnimplementedWorkflowServiceServer) GetInstanceSnapshot(context.Context, *GetInstanceRequest) (*InstanceSnapshotResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceSnapshot not implemented")
}
func (UnimplementedWorkflowServiceServer) GetActionableView(context.Context, *GetInstanceRequest) (*ActionableViewResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetActionableView not implemented")
}
func (UnimplementedWorkflowServiceServer) AddPolicy(context.Context, *AddPolicyRequest) (*MutateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AddPolicy not implemented")
}
func (UnimplementedWorkflowServiceServer) RemovePolicy(context.Context, *RemovePolicyRequest) (*MutateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RemovePolicy not implemented")
}
func (UnimplementedWorkflowServiceServer) ListPolicies(context.Context, *ListPoliciesRequest) (*ListPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListPolicies not implemented")
}
func (UnimplementedWorkflowServiceServer) AddRole(context.Context, *AddRoleRequest) (*MutateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method AddRole not implemented")
}
func (UnimplementedWorkflowServiceServer) RemoveRole(context.Context, *RemoveRoleRequest) (*MutateAck, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveRole not implemented")
}
func (UnimplementedWorkflowServiceServer) ListRoles(context.Context, *ListRolesRequest) (*ListRolesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoles not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeliverSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeliverSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeliverSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeliverSignal(ctx, req.(*DeliverSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeliverMessage(ctx, req.(*DeliverMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, req.(*ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ReassignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReassignTask(ctx, req.(*ReassignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CancelInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CancelInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CancelInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CancelInstance(ctx, req.(*CancelInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ResolveIncident_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResolveIncidentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ResolveIncident(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ResolveIncident_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ResolveIncident(ctx, req.(*ResolveIncidentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListDeadLetters(ctx, req.(*ListDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RedriveDeadLetters_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedriveDeadLettersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RedriveDeadLetters(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RedriveDeadLetters_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RedriveDeadLetters(ctx, req.(*RedriveDeadLettersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetInstanceSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetInstanceSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetInstanceSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetInstanceSnapshot(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetActionableView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetActionableView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetActionableView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetActionableView(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AddPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AddPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_AddPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AddPolicy(ctx, req.(*AddPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RemovePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemovePolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RemovePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RemovePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RemovePolicy(ctx, req.(*RemovePolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListPolicies(ctx, req.(*ListPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_AddRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).AddRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_AddRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).AddRole(ctx, req.(*AddRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_RemoveRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).RemoveRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_RemoveRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).RemoveRole(ctx, req.(*RemoveRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListRoles_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRolesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListRoles(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListRoles_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListRoles(ctx, req.(*ListRolesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wrkflw.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartInstance",
			Handler:    _WorkflowService_StartInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _WorkflowService_GetInstance_Handler,
		},
		{
			MethodName: "DeliverSignal",
			Handler:    _WorkflowService_DeliverSignal_Handler,
		},
		{
			MethodName: "DeliverMessage",
			Handler:    _WorkflowService_DeliverMessage_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _WorkflowService_ClaimTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WorkflowService_CompleteTask_Handler,
		},
		{
			MethodName: "ReassignTask",
			Handler:    _WorkflowService_ReassignTask_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WorkflowService_ListInstances_Handler,
		},
		{
			MethodName: "CancelInstance",
			Handler:    _WorkflowService_CancelInstance_Handler,
		},
		{
			MethodName: "ResolveIncident",
			Handler:    _WorkflowService_ResolveIncident_Handler,
		},
		{
			MethodName: "ListDeadLetters",
			Handler:    _WorkflowService_ListDeadLetters_Handler,
		},
		{
			MethodName: "RedriveDeadLetters",
			Handler:    _WorkflowService_RedriveDeadLetters_Handler,
		},
		{
			MethodName: "GetInstanceSnapshot",
			Handler:    _WorkflowService_GetInstanceSnapshot_Handler,
		},
		{
			MethodName: "GetActionableView",
			Handler:    _WorkflowService_GetActionableView_Handler,
		},
		{
			MethodName: "AddPolicy",
			Handler:    _WorkflowService_AddPolicy_Handler,
		},
		{
			MethodName: "RemovePolicy",
			Handler:    _WorkflowService_RemovePolicy_Handler,
		},
		{
			MethodName: "ListPolicies",
			Handler:    _WorkflowService_ListPolicies_Handler,
		},
		{
			MethodName: "AddRole",
			Handler:    _WorkflowService_AddRole_Handler,
		},
		{
			MethodName: "RemoveRole",
			Handler:    _WorkflowService_RemoveRole_Handler,
		},
		{
			MethodName: "ListRoles",
			Handler:    _WorkflowService_ListRoles_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
