// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.0
// source: workflow.proto

package workflowpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WorkflowService_StartInstance_FullMethodName  = "/wrkflw.v1.WorkflowService/StartInstance"
	WorkflowService_GetInstance_FullMethodName    = "/wrkflw.v1.WorkflowService/GetInstance"
	WorkflowService_DeliverSignal_FullMethodName  = "/wrkflw.v1.WorkflowService/DeliverSignal"
	WorkflowService_DeliverMessage_FullMethodName = "/wrkflw.v1.WorkflowService/DeliverMessage"
	WorkflowService_ClaimTask_FullMethodName      = "/wrkflw.v1.WorkflowService/ClaimTask"
	WorkflowService_CompleteTask_FullMethodName   = "/wrkflw.v1.WorkflowService/CompleteTask"
	WorkflowService_ReassignTask_FullMethodName   = "/wrkflw.v1.WorkflowService/ReassignTask"
	WorkflowService_ListInstances_FullMethodName  = "/wrkflw.v1.WorkflowService/ListInstances"
	WorkflowService_CancelInstance_FullMethodName = "/wrkflw.v1.WorkflowService/CancelInstance"
)

// WorkflowServiceClient is the client API for WorkflowService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WorkflowService exposes the workflow engine's Service facade over gRPC.
// Consumers register this service on their own grpc.Server via
// RegisterWorkflowServiceServer; this package never owns a listener.
type WorkflowServiceClient interface {
	// StartInstance creates and starts a new process instance from a definition.
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// GetInstance returns the current state of an existing instance.
	GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// DeliverSignal resumes a parked instance by delivering a named signal.
	DeliverSignal(ctx context.Context, in *DeliverSignalRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// DeliverMessage routes a message to the waiting instance by (name, correlation key).
	DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error)
	// ClaimTask authorizes the actor and claims a human task.
	ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// CompleteTask authorizes the actor and completes a human task.
	CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ReassignTask authorizes the reassigner and reassigns a human task.
	ReassignTask(ctx context.Context, in *ReassignTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
	// ListInstances returns a paginated list of instance summaries.
	ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error)
	// CancelInstance terminates a running instance (running cancel actions best-effort).
	CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error)
}

type workflowServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWorkflowServiceClient(cc grpc.ClientConnInterface) WorkflowServiceClient {
	return &workflowServiceClient{cc}
}

func (c *workflowServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_StartInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) GetInstance(ctx context.Context, in *GetInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_GetInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeliverSignal(ctx context.Context, in *DeliverSignalRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DeliverSignal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) DeliverMessage(ctx context.Context, in *DeliverMessageRequest, opts ...grpc.CallOption) (*DeliverMessageResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeliverMessageResponse)
	err := c.cc.Invoke(ctx, WorkflowService_DeliverMessage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ClaimTask(ctx context.Context, in *ClaimTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ClaimTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CompleteTask(ctx context.Context, in *CompleteTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CompleteTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ReassignTask(ctx context.Context, in *ReassignTaskRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ReassignTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) ListInstances(ctx context.Context, in *ListInstancesRequest, opts ...grpc.CallOption) (*ListInstancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListInstancesResponse)
	err := c.cc.Invoke(ctx, WorkflowService_ListInstances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *workflowServiceClient) CancelInstance(ctx context.Context, in *CancelInstanceRequest, opts ...grpc.CallOption) (*InstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceResponse)
	err := c.cc.Invoke(ctx, WorkflowService_CancelInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WorkflowServiceServer is the server API for WorkflowService service.
// All implementations must embed UnimplementedWorkflowServiceServer
// for forward compatibility.
//
// WorkflowService exposes the workflow engine's Service facade over gRPC.
// Consumers register this service on their own grpc.Server via
// RegisterWorkflowServiceServer; this package never owns a listener.
type WorkflowServiceServer interface {
	// StartInstance creates and starts a new process instance from a definition.
	StartInstance(context.Context, *StartInstanceRequest) (*InstanceResponse, error)
	// GetInstance returns the current state of an existing instance.
	GetInstance(context.Context, *GetInstanceRequest) (*InstanceResponse, error)
	// DeliverSignal resumes a parked instance by delivering a named signal.
	DeliverSignal(context.Context, *DeliverSignalRequest) (*InstanceResponse, error)
	// DeliverMessage routes a message to the waiting instance by (name, correlation key).
	DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error)
	// ClaimTask authorizes the actor and claims a human task.
	ClaimTask(context.Context, *ClaimTaskRequest) (*InstanceResponse, error)
	// CompleteTask authorizes the actor and completes a human task.
	CompleteTask(context.Context, *CompleteTaskRequest) (*InstanceResponse, error)
	// ReassignTask authorizes the reassigner and reassigns a human task.
	ReassignTask(context.Context, *ReassignTaskRequest) (*InstanceResponse, error)
	// ListInstances returns a paginated list of instance summaries.
	ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error)
	// CancelInstance terminates a running instance (running cancel actions best-effort).
	CancelInstance(context.Context, *CancelInstanceRequest) (*InstanceResponse, error)
	mustEmbedUnimplementedWorkflowServiceServer()
}

// UnimplementedWorkflowServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWorkflowServiceServer struct{}

func (UnimplementedWorkflowServiceServer) StartInstance(context.Context, *StartInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) GetInstance(context.Context, *GetInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) DeliverSignal(context.Context, *DeliverSignalRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverSignal not implemented")
}
func (UnimplementedWorkflowServiceServer) DeliverMessage(context.Context, *DeliverMessageRequest) (*DeliverMessageResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeliverMessage not implemented")
}
func (UnimplementedWorkflowServiceServer) ClaimTask(context.Context, *ClaimTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimTask not implemented")
}
func (UnimplementedWorkflowServiceServer) CompleteTask(context.Context, *CompleteTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompleteTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ReassignTask(context.Context, *ReassignTaskRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReassignTask not implemented")
}
func (UnimplementedWorkflowServiceServer) ListInstances(context.Context, *ListInstancesRequest) (*ListInstancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListInstances not implemented")
}
func (UnimplementedWorkflowServiceServer) CancelInstance(context.Context, *CancelInstanceRequest) (*InstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelInstance not implemented")
}
func (UnimplementedWorkflowServiceServer) mustEmbedUnimplementedWorkflowServiceServer() {}
func (UnimplementedWorkflowServiceServer) testEmbeddedByValue()                         {}

// UnsafeWorkflowServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WorkflowServiceServer will
// result in compilation errors.
type UnsafeWorkflowServiceServer interface {
	mustEmbedUnimplementedWorkflowServiceServer()
}

func RegisterWorkflowServiceServer(s grpc.ServiceRegistrar, srv WorkflowServiceServer) {
	// If the following call panics, it indicates UnimplementedWorkflowServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WorkflowService_ServiceDesc, srv)
}

func _WorkflowService_StartInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StartInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).StartInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_StartInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).StartInstance(ctx, req.(*StartInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_GetInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).GetInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_GetInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).GetInstance(ctx, req.(*GetInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeliverSignal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverSignalRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeliverSignal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeliverSignal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeliverSignal(ctx, req.(*DeliverSignalRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_DeliverMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeliverMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).DeliverMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_DeliverMessage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).DeliverMessage(ctx, req.(*DeliverMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ClaimTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ClaimTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ClaimTask(ctx, req.(*ClaimTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CompleteTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CompleteTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CompleteTask(ctx, req.(*CompleteTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ReassignTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReassignTaskRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ReassignTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ReassignTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ReassignTask(ctx, req.(*ReassignTaskRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_ListInstances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListInstancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).ListInstances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_ListInstances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).ListInstances(ctx, req.(*ListInstancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _WorkflowService_CancelInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WorkflowServiceServer).CancelInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WorkflowService_CancelInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WorkflowServiceServer).CancelInstance(ctx, req.(*CancelInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WorkflowService_ServiceDesc is the grpc.ServiceDesc for WorkflowService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WorkflowService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "wrkflw.v1.WorkflowService",
	HandlerType: (*WorkflowServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StartInstance",
			Handler:    _WorkflowService_StartInstance_Handler,
		},
		{
			MethodName: "GetInstance",
			Handler:    _WorkflowService_GetInstance_Handler,
		},
		{
			MethodName: "DeliverSignal",
			Handler:    _WorkflowService_DeliverSignal_Handler,
		},
		{
			MethodName: "DeliverMessage",
			Handler:    _WorkflowService_DeliverMessage_Handler,
		},
		{
			MethodName: "ClaimTask",
			Handler:    _WorkflowService_ClaimTask_Handler,
		},
		{
			MethodName: "CompleteTask",
			Handler:    _WorkflowService_CompleteTask_Handler,
		},
		{
			MethodName: "ReassignTask",
			Handler:    _WorkflowService_ReassignTask_Handler,
		},
		{
			MethodName: "ListInstances",
			Handler:    _WorkflowService_ListInstances_Handler,
		},
		{
			MethodName: "CancelInstance",
			Handler:    _WorkflowService_CancelInstance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "workflow.proto",
}
