// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: workflow.proto

package workflowpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StartInstanceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// def_ref is the process-definition reference (e.g. "my-process:1" or alias).
	DefRef string `protobuf:"bytes,1,opt,name=def_ref,json=defRef,proto3" json:"def_ref,omitempty"`
	// instance_id is the caller-supplied identifier for the new instance.
	InstanceId string `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// vars is the initial set of process variables.
	Vars          *structpb.Struct `protobuf:"bytes,3,opt,name=vars,proto3" json:"vars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartInstanceRequest) Reset() {
	*x = StartInstanceRequest{}
	mi := &file_workflow_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartInstanceRequest) ProtoMessage() {}

func (x *StartInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartInstanceRequest.ProtoReflect.Descriptor instead.
func (*StartInstanceRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{0}
}

func (x *StartInstanceRequest) GetDefRef() string {
	if x != nil {
		return x.DefRef
	}
	return ""
}

func (x *StartInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *StartInstanceRequest) GetVars() *structpb.Struct {
	if x != nil {
		return x.Vars
	}
	return nil
}

type GetInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstanceRequest) Reset() {
	*x = GetInstanceRequest{}
	mi := &file_workflow_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstanceRequest) ProtoMessage() {}

func (x *GetInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstanceRequest.ProtoReflect.Descriptor instead.
func (*GetInstanceRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type CancelInstanceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelInstanceRequest) Reset() {
	*x = CancelInstanceRequest{}
	mi := &file_workflow_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelInstanceRequest) ProtoMessage() {}

func (x *CancelInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelInstanceRequest.ProtoReflect.Descriptor instead.
func (*CancelInstanceRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{2}
}

func (x *CancelInstanceRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

type ResolveIncidentRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	IncidentId string                 `protobuf:"bytes,2,opt,name=incident_id,json=incidentId,proto3" json:"incident_id,omitempty"`
	// add_attempts grants additional execution attempts; ≤ 0 defaults to 1 in the service.
	AddAttempts   int32 `protobuf:"varint,3,opt,name=add_attempts,json=addAttempts,proto3" json:"add_attempts,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveIncidentRequest) Reset() {
	*x = ResolveIncidentRequest{}
	mi := &file_workflow_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveIncidentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveIncidentRequest) ProtoMessage() {}

func (x *ResolveIncidentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveIncidentRequest.ProtoReflect.Descriptor instead.
func (*ResolveIncidentRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{3}
}

func (x *ResolveIncidentRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *ResolveIncidentRequest) GetIncidentId() string {
	if x != nil {
		return x.IncidentId
	}
	return ""
}

func (x *ResolveIncidentRequest) GetAddAttempts() int32 {
	if x != nil {
		return x.AddAttempts
	}
	return 0
}

// DeadLetter is the gRPC projection of runtime.DeadLetter.
type DeadLetter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	InstanceId    string                 `protobuf:"bytes,2,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Topic         string                 `protobuf:"bytes,3,opt,name=topic,proto3" json:"topic,omitempty"`
	RetryCount    int32                  `protobuf:"varint,4,opt,name=retry_count,json=retryCount,proto3" json:"retry_count,omitempty"`
	LastError     string                 `protobuf:"bytes,5,opt,name=last_error,json=lastError,proto3" json:"last_error,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeadLetter) Reset() {
	*x = DeadLetter{}
	mi := &file_workflow_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeadLetter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeadLetter) ProtoMessage() {}

func (x *DeadLetter) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeadLetter.ProtoReflect.Descriptor instead.
func (*DeadLetter) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{4}
}

func (x *DeadLetter) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DeadLetter) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeadLetter) GetTopic() string {
	if x != nil {
		return x.Topic
	}
	return ""
}

func (x *DeadLetter) GetRetryCount() int32 {
	if x != nil {
		return x.RetryCount
	}
	return 0
}

func (x *DeadLetter) GetLastError() string {
	if x != nil {
		return x.LastError
	}
	return ""
}

func (x *DeadLetter) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type ListDeadLettersRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// limit is the page size (default 50, max 200 after normalization).
	Limit         int32 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersRequest) Reset() {
	*x = ListDeadLettersRequest{}
	mi := &file_workflow_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersRequest) ProtoMessage() {}

func (x *ListDeadLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersRequest.ProtoReflect.Descriptor instead.
func (*ListDeadLettersRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{5}
}

func (x *ListDeadLettersRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListDeadLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DeadLetter          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDeadLettersResponse) Reset() {
	*x = ListDeadLettersResponse{}
	mi := &file_workflow_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDeadLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDeadLettersResponse) ProtoMessage() {}

func (x *ListDeadLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDeadLettersResponse.ProtoReflect.Descriptor instead.
func (*ListDeadLettersResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{6}
}

func (x *ListDeadLettersResponse) GetItems() []*DeadLetter {
	if x != nil {
		return x.Items
	}
	return nil
}

type RedriveDeadLettersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []int64                `protobuf:"varint,1,rep,packed,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveDeadLettersRequest) Reset() {
	*x = RedriveDeadLettersRequest{}
	mi := &file_workflow_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveDeadLettersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveDeadLettersRequest) ProtoMessage() {}

func (x *RedriveDeadLettersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveDeadLettersRequest.ProtoReflect.Descriptor instead.
func (*RedriveDeadLettersRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{7}
}

func (x *RedriveDeadLettersRequest) GetIds() []int64 {
	if x != nil {
		return x.Ids
	}
	return nil
}

type RedriveDeadLettersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RedrivenCount int32                  `protobuf:"varint,1,opt,name=redriven_count,json=redrivenCount,proto3" json:"redriven_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RedriveDeadLettersResponse) Reset() {
	*x = RedriveDeadLettersResponse{}
	mi := &file_workflow_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RedriveDeadLettersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RedriveDeadLettersResponse) ProtoMessage() {}

func (x *RedriveDeadLettersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RedriveDeadLettersResponse.ProtoReflect.Descriptor instead.
func (*RedriveDeadLettersResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{8}
}

func (x *RedriveDeadLettersResponse) GetRedrivenCount() int32 {
	if x != nil {
		return x.RedrivenCount
	}
	return 0
}

// PolicyRule is a casbin RBAC policy line: subject may perform action on object.
type PolicyRule struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Subject       string                 `protobuf:"bytes,1,opt,name=subject,proto3" json:"subject,omitempty"`
	Object        string                 `protobuf:"bytes,2,opt,name=object,proto3" json:"object,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PolicyRule) Reset() {
	*x = PolicyRule{}
	mi := &file_workflow_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PolicyRule) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PolicyRule) ProtoMessage() {}

func (x *PolicyRule) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PolicyRule.ProtoReflect.Descriptor instead.
func (*PolicyRule) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{9}
}

func (x *PolicyRule) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

func (x *PolicyRule) GetObject() string {
	if x != nil {
		return x.Object
	}
	return ""
}

func (x *PolicyRule) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

// RoleBinding is a casbin grouping line: user has role.
type RoleBinding struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          string                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Role          string                 `protobuf:"bytes,2,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoleBinding) Reset() {
	*x = RoleBinding{}
	mi := &file_workflow_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoleBinding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoleBinding) ProtoMessage() {}

func (x *RoleBinding) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoleBinding.ProtoReflect.Descriptor instead.
func (*RoleBinding) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{10}
}

func (x *RoleBinding) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *RoleBinding) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type AddPolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddPolicyRequest) Reset() {
	*x = AddPolicyRequest{}
	mi := &file_workflow_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddPolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPolicyRequest) ProtoMessage() {}

func (x *AddPolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPolicyRequest.ProtoReflect.Descriptor instead.
func (*AddPolicyRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{11}
}

func (x *AddPolicyRequest) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type RemovePolicyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Rule          *PolicyRule            `protobuf:"bytes,1,opt,name=rule,proto3" json:"rule,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemovePolicyRequest) Reset() {
	*x = RemovePolicyRequest{}
	mi := &file_workflow_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemovePolicyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemovePolicyRequest) ProtoMessage() {}

func (x *RemovePolicyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemovePolicyRequest.ProtoReflect.Descriptor instead.
func (*RemovePolicyRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{12}
}

func (x *RemovePolicyRequest) GetRule() *PolicyRule {
	if x != nil {
		return x.Rule
	}
	return nil
}

type ListPoliciesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesRequest) Reset() {
	*x = ListPoliciesRequest{}
	mi := &file_workflow_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesRequest) ProtoMessage() {}

func (x *ListPoliciesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesRequest.ProtoReflect.Descriptor instead.
func (*ListPoliciesRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{13}
}

type ListPoliciesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Policies      []*PolicyRule          `protobuf:"bytes,1,rep,name=policies,proto3" json:"policies,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListPoliciesResponse) Reset() {
	*x = ListPoliciesResponse{}
	mi := &file_workflow_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListPoliciesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPoliciesResponse) ProtoMessage() {}

func (x *ListPoliciesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPoliciesResponse.ProtoReflect.Descriptor instead.
func (*ListPoliciesResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{14}
}

func (x *ListPoliciesResponse) GetPolicies() []*PolicyRule {
	if x != nil {
		return x.Policies
	}
	return nil
}

type AddRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *RoleBinding           `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AddRoleRequest) Reset() {
	*x = AddRoleRequest{}
	mi := &file_workflow_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AddRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddRoleRequest) ProtoMessage() {}

func (x *AddRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddRoleRequest.ProtoReflect.Descriptor instead.
func (*AddRoleRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{15}
}

func (x *AddRoleRequest) GetBinding() *RoleBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type RemoveRoleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Binding       *RoleBinding           `protobuf:"bytes,1,opt,name=binding,proto3" json:"binding,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveRoleRequest) Reset() {
	*x = RemoveRoleRequest{}
	mi := &file_workflow_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveRoleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveRoleRequest) ProtoMessage() {}

func (x *RemoveRoleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveRoleRequest.ProtoReflect.Descriptor instead.
func (*RemoveRoleRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveRoleRequest) GetBinding() *RoleBinding {
	if x != nil {
		return x.Binding
	}
	return nil
}

type ListRolesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesRequest) Reset() {
	*x = ListRolesRequest{}
	mi := &file_workflow_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesRequest) ProtoMessage() {}

func (x *ListRolesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesRequest.ProtoReflect.Descriptor instead.
func (*ListRolesRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{17}
}

type ListRolesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RoleBindings  []*RoleBinding         `protobuf:"bytes,1,rep,name=role_bindings,json=roleBindings,proto3" json:"role_bindings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListRolesResponse) Reset() {
	*x = ListRolesResponse{}
	mi := &file_workflow_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRolesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRolesResponse) ProtoMessage() {}

func (x *ListRolesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRolesResponse.ProtoReflect.Descriptor instead.
func (*ListRolesResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{18}
}

func (x *ListRolesResponse) GetRoleBindings() []*RoleBinding {
	if x != nil {
		return x.RoleBindings
	}
	return nil
}

// MutateAck is the result of an add/remove mutation. ok reflects casbin's
// "was the rule actually added/removed" boolean (false = already present/absent).
type MutateAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ok            bool                   `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MutateAck) Reset() {
	*x = MutateAck{}
	mi := &file_workflow_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutateAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutateAck) ProtoMessage() {}

func (x *MutateAck) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutateAck.ProtoReflect.Descriptor instead.
func (*MutateAck) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{19}
}

func (x *MutateAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

type DeliverSignalRequest struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	InstanceId string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	// signal is the name of the signal to deliver (e.g. "approved").
	Signal string `protobuf:"bytes,2,opt,name=signal,proto3" json:"signal,omitempty"`
	// payload is optional variables attached to the signal.
	Payload       *structpb.Struct `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverSignalRequest) Reset() {
	*x = DeliverSignalRequest{}
	mi := &file_workflow_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverSignalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverSignalRequest) ProtoMessage() {}

func (x *DeliverSignalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverSignalRequest.ProtoReflect.Descriptor instead.
func (*DeliverSignalRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{20}
}

func (x *DeliverSignalRequest) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *DeliverSignalRequest) GetSignal() string {
	if x != nil {
		return x.Signal
	}
	return ""
}

func (x *DeliverSignalRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type DeliverMessageRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DefRef         string                 `protobuf:"bytes,1,opt,name=def_ref,json=defRef,proto3" json:"def_ref,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	CorrelationKey string                 `protobuf:"bytes,3,opt,name=correlation_key,json=correlationKey,proto3" json:"correlation_key,omitempty"`
	Payload        *structpb.Struct       `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DeliverMessageRequest) Reset() {
	*x = DeliverMessageRequest{}
	mi := &file_workflow_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageRequest) ProtoMessage() {}

func (x *DeliverMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageRequest.ProtoReflect.Descriptor instead.
func (*DeliverMessageRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{21}
}

func (x *DeliverMessageRequest) GetDefRef() string {
	if x != nil {
		return x.DefRef
	}
	return ""
}

func (x *DeliverMessageRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DeliverMessageRequest) GetCorrelationKey() string {
	if x != nil {
		return x.CorrelationKey
	}
	return ""
}

func (x *DeliverMessageRequest) GetPayload() *structpb.Struct {
	if x != nil {
		return x.Payload
	}
	return nil
}

type Actor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Roles         []string               `protobuf:"bytes,2,rep,name=roles,proto3" json:"roles,omitempty"`
	Attributes    *structpb.Struct       `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actor) Reset() {
	*x = Actor{}
	mi := &file_workflow_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actor) ProtoMessage() {}

func (x *Actor) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actor.ProtoReflect.Descriptor instead.
func (*Actor) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{22}
}

func (x *Actor) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Actor) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

func (x *Actor) GetAttributes() *structpb.Struct {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ClaimTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     string                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimTaskRequest) Reset() {
	*x = ClaimTaskRequest{}
	mi := &file_workflow_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimTaskRequest) ProtoMessage() {}

func (x *ClaimTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimTaskRequest.ProtoReflect.Descriptor instead.
func (*ClaimTaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{23}
}

func (x *ClaimTaskRequest) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *ClaimTaskRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

type CompleteTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     string                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	Actor         *Actor                 `protobuf:"bytes,2,opt,name=actor,proto3" json:"actor,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,3,opt,name=output,proto3" json:"output,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTaskRequest) Reset() {
	*x = CompleteTaskRequest{}
	mi := &file_workflow_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTaskRequest) ProtoMessage() {}

func (x *CompleteTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTaskRequest.ProtoReflect.Descriptor instead.
func (*CompleteTaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{24}
}

func (x *CompleteTaskRequest) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *CompleteTaskRequest) GetActor() *Actor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *CompleteTaskRequest) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

type ReassignTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TaskToken     string                 `protobuf:"bytes,1,opt,name=task_token,json=taskToken,proto3" json:"task_token,omitempty"`
	From          string                 `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	To            string                 `protobuf:"bytes,3,opt,name=to,proto3" json:"to,omitempty"`
	By            *Actor                 `protobuf:"bytes,4,opt,name=by,proto3" json:"by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReassignTaskRequest) Reset() {
	*x = ReassignTaskRequest{}
	mi := &file_workflow_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReassignTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReassignTaskRequest) ProtoMessage() {}

func (x *ReassignTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReassignTaskRequest.ProtoReflect.Descriptor instead.
func (*ReassignTaskRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{25}
}

func (x *ReassignTaskRequest) GetTaskToken() string {
	if x != nil {
		return x.TaskToken
	}
	return ""
}

func (x *ReassignTaskRequest) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *ReassignTaskRequest) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *ReassignTaskRequest) GetBy() *Actor {
	if x != nil {
		return x.By
	}
	return nil
}

type ListInstancesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status filters by lifecycle state. Empty string means all statuses.
	Status string `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	// limit is the page size (default 50, max 200).
	Limit int32 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	// cursor is the opaque keyset pagination token from the previous response.
	Cursor string `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	// include_total, when true, requests total_count in the response.
	// When false (default), no count query is issued and total_count is 0.
	IncludeTotal  bool `protobuf:"varint,4,opt,name=include_total,json=includeTotal,proto3" json:"include_total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesRequest) Reset() {
	*x = ListInstancesRequest{}
	mi := &file_workflow_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesRequest) ProtoMessage() {}

func (x *ListInstancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesRequest.ProtoReflect.Descriptor instead.
func (*ListInstancesRequest) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{26}
}

func (x *ListInstancesRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ListInstancesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListInstancesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListInstancesRequest) GetIncludeTotal() bool {
	if x != nil {
		return x.IncludeTotal
	}
	return false
}

// Instance is the stable gRPC projection of engine.InstanceState.
type Instance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DefId         string                 `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`
	DefVersion    int32                  `protobuf:"varint,3,opt,name=def_version,json=defVersion,proto3" json:"def_version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	Variables     *structpb.Struct       `protobuf:"bytes,7,opt,name=variables,proto3" json:"variables,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Instance) Reset() {
	*x = Instance{}
	mi := &file_workflow_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Instance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Instance) ProtoMessage() {}

func (x *Instance) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Instance.ProtoReflect.Descriptor instead.
func (*Instance) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{27}
}

func (x *Instance) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Instance) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *Instance) GetDefVersion() int32 {
	if x != nil {
		return x.DefVersion
	}
	return 0
}

func (x *Instance) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Instance) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *Instance) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

func (x *Instance) GetVariables() *structpb.Struct {
	if x != nil {
		return x.Variables
	}
	return nil
}

// InstanceResponse carries a single Instance result.
type InstanceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Instance      *Instance              `protobuf:"bytes,1,opt,name=instance,proto3" json:"instance,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceResponse) Reset() {
	*x = InstanceResponse{}
	mi := &file_workflow_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceResponse) ProtoMessage() {}

func (x *InstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceResponse.ProtoReflect.Descriptor instead.
func (*InstanceResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{28}
}

func (x *InstanceResponse) GetInstance() *Instance {
	if x != nil {
		return x.Instance
	}
	return nil
}

// DeliverMessageResponse is the empty result of DeliverMessage.
type DeliverMessageResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeliverMessageResponse) Reset() {
	*x = DeliverMessageResponse{}
	mi := &file_workflow_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliverMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliverMessageResponse) ProtoMessage() {}

func (x *DeliverMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliverMessageResponse.ProtoReflect.Descriptor instead.
func (*DeliverMessageResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{29}
}

// InstanceSummary is a lightweight projection for list results.
type InstanceSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InstanceId    string                 `protobuf:"bytes,1,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	DefId         string                 `protobuf:"bytes,2,opt,name=def_id,json=defId,proto3" json:"def_id,omitempty"`
	DefVersion    int32                  `protobuf:"varint,3,opt,name=def_version,json=defVersion,proto3" json:"def_version,omitempty"`
	Status        string                 `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	StartedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=started_at,json=startedAt,proto3" json:"started_at,omitempty"`
	EndedAt       *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=ended_at,json=endedAt,proto3" json:"ended_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstanceSummary) Reset() {
	*x = InstanceSummary{}
	mi := &file_workflow_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstanceSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstanceSummary) ProtoMessage() {}

func (x *InstanceSummary) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstanceSummary.ProtoReflect.Descriptor instead.
func (*InstanceSummary) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{30}
}

func (x *InstanceSummary) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *InstanceSummary) GetDefId() string {
	if x != nil {
		return x.DefId
	}
	return ""
}

func (x *InstanceSummary) GetDefVersion() int32 {
	if x != nil {
		return x.DefVersion
	}
	return 0
}

func (x *InstanceSummary) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InstanceSummary) GetStartedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartedAt
	}
	return nil
}

func (x *InstanceSummary) GetEndedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndedAt
	}
	return nil
}

// ListInstancesResponse is a page of instance summaries.
type ListInstancesResponse struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Items      []*InstanceSummary     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	NextCursor string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore    bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	// total_count is set only when ListInstancesRequest.include_total was true;
	// 0 otherwise.
	TotalCount    int64 `protobuf:"varint,4,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListInstancesResponse) Reset() {
	*x = ListInstancesResponse{}
	mi := &file_workflow_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListInstancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListInstancesResponse) ProtoMessage() {}

func (x *ListInstancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_workflow_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListInstancesResponse.ProtoReflect.Descriptor instead.
func (*ListInstancesResponse) Descriptor() ([]byte, []int) {
	return file_workflow_proto_rawDescGZIP(), []int{31}
}

func (x *ListInstancesResponse) GetItems() []*InstanceSummary {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListInstancesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListInstancesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

func (x *ListInstancesResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

var File_workflow_proto protoreflect.FileDescriptor

const file_workflow_proto_rawDesc = "" +
	"\n" +
	"\x0eworkflow.proto\x12\twrkflw.v1\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"}\n" +
	"\x14StartInstanceRequest\x12\x17\n" +
	"\adef_ref\x18\x01 \x01(\tR\x06defRef\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12+\n" +
	"\x04vars\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x04vars\"5\n" +
	"\x12GetInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"8\n" +
	"\x15CancelInstanceRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\"}\n" +
	"\x16ResolveIncidentRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x1f\n" +
	"\vincident_id\x18\x02 \x01(\tR\n" +
	"incidentId\x12!\n" +
	"\fadd_attempts\x18\x03 \x01(\x05R\vaddAttempts\"\xce\x01\n" +
	"\n" +
	"DeadLetter\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1f\n" +
	"\vinstance_id\x18\x02 \x01(\tR\n" +
	"instanceId\x12\x14\n" +
	"\x05topic\x18\x03 \x01(\tR\x05topic\x12\x1f\n" +
	"\vretry_count\x18\x04 \x01(\x05R\n" +
	"retryCount\x12\x1d\n" +
	"\n" +
	"last_error\x18\x05 \x01(\tR\tlastError\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\".\n" +
	"\x16ListDeadLettersRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x05R\x05limit\"F\n" +
	"\x17ListDeadLettersResponse\x12+\n" +
	"\x05items\x18\x01 \x03(\v2\x15.wrkflw.v1.DeadLetterR\x05items\"-\n" +
	"\x19RedriveDeadLettersRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\x03R\x03ids\"C\n" +
	"\x1aRedriveDeadLettersResponse\x12%\n" +
	"\x0eredriven_count\x18\x01 \x01(\x05R\rredrivenCount\"V\n" +
	"\n" +
	"PolicyRule\x12\x18\n" +
	"\asubject\x18\x01 \x01(\tR\asubject\x12\x16\n" +
	"\x06object\x18\x02 \x01(\tR\x06object\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"5\n" +
	"\vRoleBinding\x12\x12\n" +
	"\x04user\x18\x01 \x01(\tR\x04user\x12\x12\n" +
	"\x04role\x18\x02 \x01(\tR\x04role\"=\n" +
	"\x10AddPolicyRequest\x12)\n" +
	"\x04rule\x18\x01 \x01(\v2\x15.wrkflw.v1.PolicyRuleR\x04rule\"@\n" +
	"\x13RemovePolicyRequest\x12)\n" +
	"\x04rule\x18\x01 \x01(\v2\x15.wrkflw.v1.PolicyRuleR\x04rule\"\x15\n" +
	"\x13ListPoliciesRequest\"I\n" +
	"\x14ListPoliciesResponse\x121\n" +
	"\bpolicies\x18\x01 \x03(\v2\x15.wrkflw.v1.PolicyRuleR\bpolicies\"B\n" +
	"\x0eAddRoleRequest\x120\n" +
	"\abinding\x18\x01 \x01(\v2\x16.wrkflw.v1.RoleBindingR\abinding\"E\n" +
	"\x11RemoveRoleRequest\x120\n" +
	"\abinding\x18\x01 \x01(\v2\x16.wrkflw.v1.RoleBindingR\abinding\"\x12\n" +
	"\x10ListRolesRequest\"P\n" +
	"\x11ListRolesResponse\x12;\n" +
	"\rrole_bindings\x18\x01 \x03(\v2\x16.wrkflw.v1.RoleBindingR\froleBindings\"\x1b\n" +
	"\tMutateAck\x12\x0e\n" +
	"\x02ok\x18\x01 \x01(\bR\x02ok\"\x82\x01\n" +
	"\x14DeliverSignalRequest\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x16\n" +
	"\x06signal\x18\x02 \x01(\tR\x06signal\x121\n" +
	"\apayload\x18\x03 \x01(\v2\x17.google.protobuf.StructR\apayload\"\xa0\x01\n" +
	"\x15DeliverMessageRequest\x12\x17\n" +
	"\adef_ref\x18\x01 \x01(\tR\x06defRef\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12'\n" +
	"\x0fcorrelation_key\x18\x03 \x01(\tR\x0ecorrelationKey\x121\n" +
	"\apayload\x18\x04 \x01(\v2\x17.google.protobuf.StructR\apayload\"f\n" +
	"\x05Actor\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05roles\x18\x02 \x03(\tR\x05roles\x127\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2\x17.google.protobuf.StructR\n" +
	"attributes\"Y\n" +
	"\x10ClaimTaskRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\tR\ttaskToken\x12&\n" +
	"\x05actor\x18\x02 \x01(\v2\x10.wrkflw.v1.ActorR\x05actor\"\x8d\x01\n" +
	"\x13CompleteTaskRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\tR\ttaskToken\x12&\n" +
	"\x05actor\x18\x02 \x01(\v2\x10.wrkflw.v1.ActorR\x05actor\x12/\n" +
	"\x06output\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x06output\"z\n" +
	"\x13ReassignTaskRequest\x12\x1d\n" +
	"\n" +
	"task_token\x18\x01 \x01(\tR\ttaskToken\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\tR\x02to\x12 \n" +
	"\x02by\x18\x04 \x01(\v2\x10.wrkflw.v1.ActorR\x02by\"\x81\x01\n" +
	"\x14ListInstancesRequest\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12#\n" +
	"\rinclude_total\x18\x04 \x01(\bR\fincludeTotal\"\xa4\x02\n" +
	"\bInstance\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06def_id\x18\x02 \x01(\tR\x05defId\x12\x1f\n" +
	"\vdef_version\x18\x03 \x01(\x05R\n" +
	"defVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\x125\n" +
	"\tvariables\x18\a \x01(\v2\x17.google.protobuf.StructR\tvariables\"C\n" +
	"\x10InstanceResponse\x12/\n" +
	"\binstance\x18\x01 \x01(\v2\x13.wrkflw.v1.InstanceR\binstance\"\x18\n" +
	"\x16DeliverMessageResponse\"\xf4\x01\n" +
	"\x0fInstanceSummary\x12\x1f\n" +
	"\vinstance_id\x18\x01 \x01(\tR\n" +
	"instanceId\x12\x15\n" +
	"\x06def_id\x18\x02 \x01(\tR\x05defId\x12\x1f\n" +
	"\vdef_version\x18\x03 \x01(\x05R\n" +
	"defVersion\x12\x16\n" +
	"\x06status\x18\x04 \x01(\tR\x06status\x129\n" +
	"\n" +
	"started_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tstartedAt\x125\n" +
	"\bended_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\aendedAt\"\xa6\x01\n" +
	"\x15ListInstancesResponse\x120\n" +
	"\x05items\x18\x01 \x03(\v2\x1a.wrkflw.v1.InstanceSummaryR\x05items\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\x12\x1f\n" +
	"\vtotal_count\x18\x04 \x01(\x03R\n" +
	"totalCount2\x84\v\n" +
	"\x0fWorkflowService\x12M\n" +
	"\rStartInstance\x12\x1f.wrkflw.v1.StartInstanceRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12I\n" +
	"\vGetInstance\x12\x1d.wrkflw.v1.GetInstanceRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12M\n" +
	"\rDeliverSignal\x12\x1f.wrkflw.v1.DeliverSignalRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12U\n" +
	"\x0eDeliverMessage\x12 .wrkflw.v1.DeliverMessageRequest\x1a!.wrkflw.v1.DeliverMessageResponse\x12E\n" +
	"\tClaimTask\x12\x1b.wrkflw.v1.ClaimTaskRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12K\n" +
	"\fCompleteTask\x12\x1e.wrkflw.v1.CompleteTaskRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12K\n" +
	"\fReassignTask\x12\x1e.wrkflw.v1.ReassignTaskRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12R\n" +
	"\rListInstances\x12\x1f.wrkflw.v1.ListInstancesRequest\x1a .wrkflw.v1.ListInstancesResponse\x12O\n" +
	"\x0eCancelInstance\x12 .wrkflw.v1.CancelInstanceRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12Q\n" +
	"\x0fResolveIncident\x12!.wrkflw.v1.ResolveIncidentRequest\x1a\x1b.wrkflw.v1.InstanceResponse\x12X\n" +
	"\x0fListDeadLetters\x12!.wrkflw.v1.ListDeadLettersRequest\x1a\".wrkflw.v1.ListDeadLettersResponse\x12a\n" +
	"\x12RedriveDeadLetters\x12$.wrkflw.v1.RedriveDeadLettersRequest\x1a%.wrkflw.v1.RedriveDeadLettersResponse\x12>\n" +
	"\tAddPolicy\x12\x1b.wrkflw.v1.AddPolicyRequest\x1a\x14.wrkflw.v1.MutateAck\x12D\n" +
	"\fRemovePolicy\x12\x1e.wrkflw.v1.RemovePolicyRequest\x1a\x14.wrkflw.v1.MutateAck\x12O\n" +
	"\fListPolicies\x12\x1e.wrkflw.v1.ListPoliciesRequest\x1a\x1f.wrkflw.v1.ListPoliciesResponse\x12:\n" +
	"\aAddRole\x12\x19.wrkflw.v1.AddRoleRequest\x1a\x14.wrkflw.v1.MutateAck\x12@\n" +
	"\n" +
	"RemoveRole\x12\x1c.wrkflw.v1.RemoveRoleRequest\x1a\x14.wrkflw.v1.MutateAck\x12F\n" +
	"\tListRoles\x12\x1b.wrkflw.v1.ListRolesRequest\x1a\x1c.wrkflw.v1.ListRolesResponseBFZDgithub.com/zakyalvan/krtlwrkflw/transport/grpc/workflowpb;workflowpbb\x06proto3"

var (
	file_workflow_proto_rawDescOnce sync.Once
	file_workflow_proto_rawDescData []byte
)

func file_workflow_proto_rawDescGZIP() []byte {
	file_workflow_proto_rawDescOnce.Do(func() {
		file_workflow_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)))
	})
	return file_workflow_proto_rawDescData
}

var file_workflow_proto_msgTypes = make([]protoimpl.MessageInfo, 32)
var file_workflow_proto_goTypes = []any{
	(*StartInstanceRequest)(nil),       // 0: wrkflw.v1.StartInstanceRequest
	(*GetInstanceRequest)(nil),         // 1: wrkflw.v1.GetInstanceRequest
	(*CancelInstanceRequest)(nil),      // 2: wrkflw.v1.CancelInstanceRequest
	(*ResolveIncidentRequest)(nil),     // 3: wrkflw.v1.ResolveIncidentRequest
	(*DeadLetter)(nil),                 // 4: wrkflw.v1.DeadLetter
	(*ListDeadLettersRequest)(nil),     // 5: wrkflw.v1.ListDeadLettersRequest
	(*ListDeadLettersResponse)(nil),    // 6: wrkflw.v1.ListDeadLettersResponse
	(*RedriveDeadLettersRequest)(nil),  // 7: wrkflw.v1.RedriveDeadLettersRequest
	(*RedriveDeadLettersResponse)(nil), // 8: wrkflw.v1.RedriveDeadLettersResponse
	(*PolicyRule)(nil),                 // 9: wrkflw.v1.PolicyRule
	(*RoleBinding)(nil),                // 10: wrkflw.v1.RoleBinding
	(*AddPolicyRequest)(nil),           // 11: wrkflw.v1.AddPolicyRequest
	(*RemovePolicyRequest)(nil),        // 12: wrkflw.v1.RemovePolicyRequest
	(*ListPoliciesRequest)(nil),        // 13: wrkflw.v1.ListPoliciesRequest
	(*ListPoliciesResponse)(nil),       // 14: wrkflw.v1.ListPoliciesResponse
	(*AddRoleRequest)(nil),             // 15: wrkflw.v1.AddRoleRequest
	(*RemoveRoleRequest)(nil),          // 16: wrkflw.v1.RemoveRoleRequest
	(*ListRolesRequest)(nil),           // 17: wrkflw.v1.ListRolesRequest
	(*ListRolesResponse)(nil),          // 18: wrkflw.v1.ListRolesResponse
	(*MutateAck)(nil),                  // 19: wrkflw.v1.MutateAck
	(*DeliverSignalRequest)(nil),       // 20: wrkflw.v1.DeliverSignalRequest
	(*DeliverMessageRequest)(nil),      // 21: wrkflw.v1.DeliverMessageRequest
	(*Actor)(nil),                      // 22: wrkflw.v1.Actor
	(*ClaimTaskRequest)(nil),           // 23: wrkflw.v1.ClaimTaskRequest
	(*CompleteTaskRequest)(nil),        // 24: wrkflw.v1.CompleteTaskRequest
	(*ReassignTaskRequest)(nil),        // 25: wrkflw.v1.ReassignTaskRequest
	(*ListInstancesRequest)(nil),       // 26: wrkflw.v1.ListInstancesRequest
	(*Instance)(nil),                   // 27: wrkflw.v1.Instance
	(*InstanceResponse)(nil),           // 28: wrkflw.v1.InstanceResponse
	(*DeliverMessageResponse)(nil),     // 29: wrkflw.v1.DeliverMessageResponse
	(*InstanceSummary)(nil),            // 30: wrkflw.v1.InstanceSummary
	(*ListInstancesResponse)(nil),      // 31: wrkflw.v1.ListInstancesResponse
	(*structpb.Struct)(nil),            // 32: google.protobuf.Struct
	(*timestamppb.Timestamp)(nil),      // 33: google.protobuf.Timestamp
}
var file_workflow_proto_depIdxs = []int32{
	32, // 0: wrkflw.v1.StartInstanceRequest.vars:type_name -> google.protobuf.Struct
	33, // 1: wrkflw.v1.DeadLetter.created_at:type_name -> google.protobuf.Timestamp
	4,  // 2: wrkflw.v1.ListDeadLettersResponse.items:type_name -> wrkflw.v1.DeadLetter
	9,  // 3: wrkflw.v1.AddPolicyRequest.rule:type_name -> wrkflw.v1.PolicyRule
	9,  // 4: wrkflw.v1.RemovePolicyRequest.rule:type_name -> wrkflw.v1.PolicyRule
	9,  // 5: wrkflw.v1.ListPoliciesResponse.policies:type_name -> wrkflw.v1.PolicyRule
	10, // 6: wrkflw.v1.AddRoleRequest.binding:type_name -> wrkflw.v1.RoleBinding
	10, // 7: wrkflw.v1.RemoveRoleRequest.binding:type_name -> wrkflw.v1.RoleBinding
	10, // 8: wrkflw.v1.ListRolesResponse.role_bindings:type_name -> wrkflw.v1.RoleBinding
	32, // 9: wrkflw.v1.DeliverSignalRequest.payload:type_name -> google.protobuf.Struct
	32, // 10: wrkflw.v1.DeliverMessageRequest.payload:type_name -> google.protobuf.Struct
	32, // 11: wrkflw.v1.Actor.attributes:type_name -> google.protobuf.Struct
	22, // 12: wrkflw.v1.ClaimTaskRequest.actor:type_name -> wrkflw.v1.Actor
	22, // 13: wrkflw.v1.CompleteTaskRequest.actor:type_name -> wrkflw.v1.Actor
	32, // 14: wrkflw.v1.CompleteTaskRequest.output:type_name -> google.protobuf.Struct
	22, // 15: wrkflw.v1.ReassignTaskRequest.by:type_name -> wrkflw.v1.Actor
	33, // 16: wrkflw.v1.Instance.started_at:type_name -> google.protobuf.Timestamp
	33, // 17: wrkflw.v1.Instance.ended_at:type_name -> google.protobuf.Timestamp
	32, // 18: wrkflw.v1.Instance.variables:type_name -> google.protobuf.Struct
	27, // 19: wrkflw.v1.InstanceResponse.instance:type_name -> wrkflw.v1.Instance
	33, // 20: wrkflw.v1.InstanceSummary.started_at:type_name -> google.protobuf.Timestamp
	33, // 21: wrkflw.v1.InstanceSummary.ended_at:type_name -> google.protobuf.Timestamp
	30, // 22: wrkflw.v1.ListInstancesResponse.items:type_name -> wrkflw.v1.InstanceSummary
	0,  // 23: wrkflw.v1.WorkflowService.StartInstance:input_type -> wrkflw.v1.StartInstanceRequest
	1,  // 24: wrkflw.v1.WorkflowService.GetInstance:input_type -> wrkflw.v1.GetInstanceRequest
	20, // 25: wrkflw.v1.WorkflowService.DeliverSignal:input_type -> wrkflw.v1.DeliverSignalRequest
	21, // 26: wrkflw.v1.WorkflowService.DeliverMessage:input_type -> wrkflw.v1.DeliverMessageRequest
	23, // 27: wrkflw.v1.WorkflowService.ClaimTask:input_type -> wrkflw.v1.ClaimTaskRequest
	24, // 28: wrkflw.v1.WorkflowService.CompleteTask:input_type -> wrkflw.v1.CompleteTaskRequest
	25, // 29: wrkflw.v1.WorkflowService.ReassignTask:input_type -> wrkflw.v1.ReassignTaskRequest
	26, // 30: wrkflw.v1.WorkflowService.ListInstances:input_type -> wrkflw.v1.ListInstancesRequest
	2,  // 31: wrkflw.v1.WorkflowService.CancelInstance:input_type -> wrkflw.v1.CancelInstanceRequest
	3,  // 32: wrkflw.v1.WorkflowService.ResolveIncident:input_type -> wrkflw.v1.ResolveIncidentRequest
	5,  // 33: wrkflw.v1.WorkflowService.ListDeadLetters:input_type -> wrkflw.v1.ListDeadLettersRequest
	7,  // 34: wrkflw.v1.WorkflowService.RedriveDeadLetters:input_type -> wrkflw.v1.RedriveDeadLettersRequest
	11, // 35: wrkflw.v1.WorkflowService.AddPolicy:input_type -> wrkflw.v1.AddPolicyRequest
	12, // 36: wrkflw.v1.WorkflowService.RemovePolicy:input_type -> wrkflw.v1.RemovePolicyRequest
	13, // 37: wrkflw.v1.WorkflowService.ListPolicies:input_type -> wrkflw.v1.ListPoliciesRequest
	15, // 38: wrkflw.v1.WorkflowService.AddRole:input_type -> wrkflw.v1.AddRoleRequest
	16, // 39: wrkflw.v1.WorkflowService.RemoveRole:input_type -> wrkflw.v1.RemoveRoleRequest
	17, // 40: wrkflw.v1.WorkflowService.ListRoles:input_type -> wrkflw.v1.ListRolesRequest
	28, // 41: wrkflw.v1.WorkflowService.StartInstance:output_type -> wrkflw.v1.InstanceResponse
	28, // 42: wrkflw.v1.WorkflowService.GetInstance:output_type -> wrkflw.v1.InstanceResponse
	28, // 43: wrkflw.v1.WorkflowService.DeliverSignal:output_type -> wrkflw.v1.InstanceResponse
	29, // 44: wrkflw.v1.WorkflowService.DeliverMessage:output_type -> wrkflw.v1.DeliverMessageResponse
	28, // 45: wrkflw.v1.WorkflowService.ClaimTask:output_type -> wrkflw.v1.InstanceResponse
	28, // 46: wrkflw.v1.WorkflowService.CompleteTask:output_type -> wrkflw.v1.InstanceResponse
	28, // 47: wrkflw.v1.WorkflowService.ReassignTask:output_type -> wrkflw.v1.InstanceResponse
	31, // 48: wrkflw.v1.WorkflowService.ListInstances:output_type -> wrkflw.v1.ListInstancesResponse
	28, // 49: wrkflw.v1.WorkflowService.CancelInstance:output_type -> wrkflw.v1.InstanceResponse
	28, // 50: wrkflw.v1.WorkflowService.ResolveIncident:output_type -> wrkflw.v1.InstanceResponse
	6,  // 51: wrkflw.v1.WorkflowService.ListDeadLetters:output_type -> wrkflw.v1.ListDeadLettersResponse
	8,  // 52: wrkflw.v1.WorkflowService.RedriveDeadLetters:output_type -> wrkflw.v1.RedriveDeadLettersResponse
	19, // 53: wrkflw.v1.WorkflowService.AddPolicy:output_type -> wrkflw.v1.MutateAck
	19, // 54: wrkflw.v1.WorkflowService.RemovePolicy:output_type -> wrkflw.v1.MutateAck
	14, // 55: wrkflw.v1.WorkflowService.ListPolicies:output_type -> wrkflw.v1.ListPoliciesResponse
	19, // 56: wrkflw.v1.WorkflowService.AddRole:output_type -> wrkflw.v1.MutateAck
	19, // 57: wrkflw.v1.WorkflowService.RemoveRole:output_type -> wrkflw.v1.MutateAck
	18, // 58: wrkflw.v1.WorkflowService.ListRoles:output_type -> wrkflw.v1.ListRolesResponse
	41, // [41:59] is the sub-list for method output_type
	23, // [23:41] is the sub-list for method input_type
	23, // [23:23] is the sub-list for extension type_name
	23, // [23:23] is the sub-list for extension extendee
	0,  // [0:23] is the sub-list for field type_name
}

func init() { file_workflow_proto_init() }
func file_workflow_proto_init() {
	if File_workflow_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_workflow_proto_rawDesc), len(file_workflow_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   32,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_workflow_proto_goTypes,
		DependencyIndexes: file_workflow_proto_depIdxs,
		MessageInfos:      file_workflow_proto_msgTypes,
	}.Build()
	File_workflow_proto = out.File
	file_workflow_proto_goTypes = nil
	file_workflow_proto_depIdxs = nil
}
