// Code generated by MockGen. DO NOT EDIT.
// Source: opsadmin.go
//
// Generated by this command:
//
//	mockgen -source=opsadmin.go -package=servicetest -destination=servicetest/opsadmin_mock.go -typed
//

// Package servicetest is a generated GoMock package.
package servicetest

import (
	context "context"
	reflect "reflect"

	kernel "github.com/kartaladev/wrkflw/runtime/kernel"
	gomock "go.uber.org/mock/gomock"
)

// MockRelayStatsAdmin is a mock of RelayStatsAdmin interface.
type MockRelayStatsAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockRelayStatsAdminMockRecorder
	isgomock struct{}
}

// MockRelayStatsAdminMockRecorder is the mock recorder for MockRelayStatsAdmin.
type MockRelayStatsAdminMockRecorder struct {
	mock *MockRelayStatsAdmin
}

// NewMockRelayStatsAdmin creates a new mock instance.
func NewMockRelayStatsAdmin(ctrl *gomock.Controller) *MockRelayStatsAdmin {
	mock := &MockRelayStatsAdmin{ctrl: ctrl}
	mock.recorder = &MockRelayStatsAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRelayStatsAdmin) EXPECT() *MockRelayStatsAdminMockRecorder {
	return m.recorder
}

// OutboxStats mocks base method.
func (m *MockRelayStatsAdmin) OutboxStats(ctx context.Context) (kernel.OutboxStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OutboxStats", ctx)
	ret0, _ := ret[0].(kernel.OutboxStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OutboxStats indicates an expected call of OutboxStats.
func (mr *MockRelayStatsAdminMockRecorder) OutboxStats(ctx any) *MockRelayStatsAdminOutboxStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OutboxStats", reflect.TypeOf((*MockRelayStatsAdmin)(nil).OutboxStats), ctx)
	return &MockRelayStatsAdminOutboxStatsCall{Call: call}
}

// MockRelayStatsAdminOutboxStatsCall wrap *gomock.Call
type MockRelayStatsAdminOutboxStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockRelayStatsAdminOutboxStatsCall) Return(arg0 kernel.OutboxStats, arg1 error) *MockRelayStatsAdminOutboxStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockRelayStatsAdminOutboxStatsCall) Do(f func(context.Context) (kernel.OutboxStats, error)) *MockRelayStatsAdminOutboxStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockRelayStatsAdminOutboxStatsCall) DoAndReturn(f func(context.Context) (kernel.OutboxStats, error)) *MockRelayStatsAdminOutboxStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// MockTimerAdmin is a mock of TimerAdmin interface.
type MockTimerAdmin struct {
	ctrl     *gomock.Controller
	recorder *MockTimerAdminMockRecorder
	isgomock struct{}
}

// MockTimerAdminMockRecorder is the mock recorder for MockTimerAdmin.
type MockTimerAdminMockRecorder struct {
	mock *MockTimerAdmin
}

// NewMockTimerAdmin creates a new mock instance.
func NewMockTimerAdmin(ctrl *gomock.Controller) *MockTimerAdmin {
	mock := &MockTimerAdmin{ctrl: ctrl}
	mock.recorder = &MockTimerAdminMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimerAdmin) EXPECT() *MockTimerAdminMockRecorder {
	return m.recorder
}

// ListArmedPage mocks base method.
func (m *MockTimerAdmin) ListArmedPage(ctx context.Context, filter kernel.ArmedTimerFilter) (kernel.ArmedTimerPage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListArmedPage", ctx, filter)
	ret0, _ := ret[0].(kernel.ArmedTimerPage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListArmedPage indicates an expected call of ListArmedPage.
func (mr *MockTimerAdminMockRecorder) ListArmedPage(ctx, filter any) *MockTimerAdminListArmedPageCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListArmedPage", reflect.TypeOf((*MockTimerAdmin)(nil).ListArmedPage), ctx, filter)
	return &MockTimerAdminListArmedPageCall{Call: call}
}

// MockTimerAdminListArmedPageCall wrap *gomock.Call
type MockTimerAdminListArmedPageCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTimerAdminListArmedPageCall) Return(arg0 kernel.ArmedTimerPage, arg1 error) *MockTimerAdminListArmedPageCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTimerAdminListArmedPageCall) Do(f func(context.Context, kernel.ArmedTimerFilter) (kernel.ArmedTimerPage, error)) *MockTimerAdminListArmedPageCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTimerAdminListArmedPageCall) DoAndReturn(f func(context.Context, kernel.ArmedTimerFilter) (kernel.ArmedTimerPage, error)) *MockTimerAdminListArmedPageCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}

// Stats mocks base method.
func (m *MockTimerAdmin) Stats(ctx context.Context) (kernel.TimerStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx)
	ret0, _ := ret[0].(kernel.TimerStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockTimerAdminMockRecorder) Stats(ctx any) *MockTimerAdminStatsCall {
	mr.mock.ctrl.T.Helper()
	call := mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockTimerAdmin)(nil).Stats), ctx)
	return &MockTimerAdminStatsCall{Call: call}
}

// MockTimerAdminStatsCall wrap *gomock.Call
type MockTimerAdminStatsCall struct {
	*gomock.Call
}

// Return rewrite *gomock.Call.Return
func (c *MockTimerAdminStatsCall) Return(arg0 kernel.TimerStats, arg1 error) *MockTimerAdminStatsCall {
	c.Call = c.Call.Return(arg0, arg1)
	return c
}

// Do rewrite *gomock.Call.Do
func (c *MockTimerAdminStatsCall) Do(f func(context.Context) (kernel.TimerStats, error)) *MockTimerAdminStatsCall {
	c.Call = c.Call.Do(f)
	return c
}

// DoAndReturn rewrite *gomock.Call.DoAndReturn
func (c *MockTimerAdminStatsCall) DoAndReturn(f func(context.Context) (kernel.TimerStats, error)) *MockTimerAdminStatsCall {
	c.Call = c.Call.DoAndReturn(f)
	return c
}
